server:
  port: 8080

spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/webhooks
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: webhook-workers-${HOSTNAME}
      auto-offset-reset: earliest
      enable-auto-commit: false
      concurrency: 2
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      ack-mode: manual
  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info,metrics
  metrics:
    tags:
      application: webhook-worker
    distribution:
      percentiles-histogram:
        webhook: true
      percentiles:
        webhook: 0.5, 0.95, 0.99, 0.999
      slos:
        webhook: 100ms, 500ms, 1s, 5s

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.rnvo.notifier: INFO
    resilience4j: INFO

app:
  fairness:
    limit: ${NOTIFIER_FAIRNESS_LIMIT:100}
    interval-seconds: ${NOTIFIER_FAIRNESS_INTERVAL_SECONDS:false}
